### ISSUE TITLE
Add travis requirements for Typhorus

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/github-pages-template#22]
See wiki at https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis

Need to add 

```yaml
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
```
